services:
  - type: web
    name: youtube-mp3-converter
    env: node
    region: singapore
    plan: free
    buildCommand: |
      npm install
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /opt/render/project/src/yt-dlp
      chmod a+rx /opt/render/project/src/yt-dlp
      export PATH="/opt/render/project/src:$PATH"
    startCommand: npm start
    healthCheckPath: /api/health